# Generated by Django 3.1.3 on 2020-11-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201124_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='meanning',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='word',
        ),
    ]
