# Generated by Django 3.1.3 on 2020-11-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201124_0745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Wordnote',
        ),
    ]
