# Generated by Django 3.1.3 on 2020-11-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201124_0747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wordnote',
            new_name='EnglishWord',
        ),
    ]
