# Generated by Django 3.1.3 on 2020-11-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201124_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='englishword',
            old_name='meanning',
            new_name='mean',
        ),
    ]
